### PR TITLE
Fix useless require to Babel (fixes #6)

### LINKED ISSUE #6: Error: Cannot find module 'babel/polyfill'
Hello,

Babel is actually required to run eslint-nibble, so it fails if Babel is not installed with this error :
```js
module.js:338
    throw err;
          ^
Error: Cannot find module 'babel/polyfill'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/.../my-project/node_modules/eslint-nibble/index.js:4:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

### PR DESCRIPTION
**Pull request by cmalard**
;)

### CODE REVIEW

**Comment by cmalard** [comment]
How do you mange versions ? Do you want I upgrade it to 0.1.1 ?

**Comment by IanVS** [comment]
I'll do the version bump tonight, thanks.  Were you able to verify that it works correctly with this change?

I really need to add some tests.....

**Comment by cmalard** [comment]
It works like a charm ;)

**Comment by IanVS** [comment]
Great, thanks!

**Comment by IanVS** [comment]
`0.1.1` is published.  Thanks again for the help.

**Pull request merged**
