### PR TITLE
Use require.resolve to support cases when when formatters installed on the same level as eslint-nibbler

### PR DESCRIPTION
**Pull request by princed**
E.g. npm dedupe or npm@3 or just direct formatter usage in the linted module.

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks, this is a good idea, and something I didn't consider.  Before I merge, can you also add a test?

**Comment by princed** [comment]
No problem, what would you like to test? I'm slightly confused with it.

**Comment by IanVS** [comment]
I'll try to think about a good way to do this, but anytime I make a bug fix I want to add a test which fails without the fix and passes with it.   It may also be possible to install npm@3 within a CI build.

**Comment by IanVS** [comment]
OK, I can't figure out how to test this either, since it won't fail unless the project is installed as a dependency and all of it's own deps are flattened outside of it (which won't happen in CI).  So, merging as is, and thanks again!

**Comment by princed** [comment]
Ok, thanks for merging!

**Pull request merged**
