### PR TITLE
Change babel preset, because previous compiled code is not running

### PR DESCRIPTION
**Pull request by dphov**
Sorry about that 😐

### CODE REVIEW

**Comment by IanVS** [comment]
I tested out your other change before merging and it seemed okay. What is the problem now, exactly? (I can't check right now).

**Comment by dphov** [comment]
I'm updated eslint-nibble to 3.1.1. After I ran it, program crashed because of 'X function not found', so then I compile it with es2015 preset and this make it runnable

**Comment by IanVS** [comment]
Shoot, it looks like somehow I published a bad version, I don't think it has to do with your change.  I'll fix and push up 3.1.2.

**Comment by IanVS** [comment]
Okay, It seems I published when I had some uncommitted changes, and the compiled files pushed to npm were therefore broken.  3.1.2 is now published which should fix it.  Thanks for the heads-up, @dphov.

**Pull request closed without merging**
