### PR TITLE
Add cache flag

### LINKED ISSUE #41: Add --cache flag
ESLint supports a `--cache` flag that can dramatically speed up linting. Adding this to nibble would also speed it up (presumably).

### PR DESCRIPTION
**Pull request by aboyton**
Closes #41 

For some reason, this seems to create the `.eslintcache` file correctly, but it doesn't seem to speed anything up, although I'm having trouble debugging exactly why.

### CODE REVIEW

**Comment by IanVS** [comment]
Thanks @aboyton.  I haven't forgotten about this, just been very busy lately.  I'll take a look soon and try to verify whether it's working.

**Comment by aboyton** [comment]
Thanks. No rush, more of a "nice to have". Linting for us takes a few minutes and so caching is nice, that said my normal workflow doesn't include using nibble and so it's not particularly blocking.

**Comment by IanVS** [comment]
This works great!   I wish I had tested and merged earlier.

image

**Comment by aboyton** [comment]
I had completely forgotten about this PR. Glad that you found it useful.

**Pull request merged**
