### PR TITLE
Replace iojs by stable in travis config

### PR DESCRIPTION
**Pull request by zckrs**

### CODE REVIEW

**Comment by IanVS** [comment]
Do you see any value in keeping `iojs` and adding `stable` rather than replacing?

**Comment by zckrs** [comment]
On https://iojs.org/

> io.js has merged with the Node.js project again.

IMO keep `iojs` is not necessary

**Comment by IanVS** [comment]
OK, based on https://twitter.com/seldo/status/646463678410174465, not many downloads of iojs anymore, so this probably makes sense.  Thanks!

**Comment by zckrs** [comment]
You are welcome :-)

**Pull request merged**
